version: '2.1'

services:
  nest:
    image: nest
    build: .
    environment:
      DATASOURCE: "mongodb://mongoadmin:mongoadmin@mongo-docker:27017/node-mongo-crud?ssl=false&authSource=admin&retryWrites=true"
      NODE_ENV: production
    ports:
      - 3001:3001
networks:
  default:
    external:
      name: docker-local