version: '2.1'

services:
  nest-debug:
    image: nest
    build: .
    environment:
      DATASOURCE: "mongodb://mongoadmin:mongoadmin@mongo-docker:27017/node-mongo-crud?ssl=false&authSource=admin&retryWrites=true"
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: npm run start:debug
networks:
  default:
    external:
      name: docker-local